name: "[TWRP][berlna] Motorola Edge 2021"
on:
  workflow_dispatch:
env:
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: "Cleanup Environment"
         uses: rokibhasansagar/slimhub_actions@main

       - name: Initializing environment
         run: |
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install curl libstdc++6 git wget rsync aria2 repo
            git config --global user.name "januur"
            git config --global user.email "fazuultree@gmail.com"
            git clone https://github.com/akhilnarang/scripts --depth=1 --single-branch
            cd scripts
            sudo -E bash setup/android_build_env.sh

       - name: "Sync & compile"
         run: |
            mkdir ~/twrp
            cd ~/twrp
            repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1 --depth=1
            repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
            cd ~/twrp/build
            git fetch https://gerrit.twrp.me/android_build refs/changes/45/5445/1 && git cherry-pick FETCH_HEAD
            cd ~/twrp
            git clone https://github.com/SyberHexen/AnyKernel3 --depth=1 -b master+twrp bootable/recovery/installer
            git clone https://github.com/SyberHexen/android_device_motorola_berlna-twrp --depth=1 -b twrp-12.1 device/motorola/berlna
            echo "TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888" >> device/motorola/berlna/BoardConfig.mk
            echo "TARGET_RECOVERY_FORCE_PIXEL_FORMAT := RGBX_8888" >> device/motorola/berlna/BoardConfig.mk
            export ALLOW_MISSING_DEPENDENCIES=true
            export LC_ALL=C
            export TARGET_PREBUILT_KERNEL=device/motorola/berlna/prebuilt/Image
            . build/envsetup.sh
            lunch twrp_berlna-eng
            mka bootimage -j$(nproc --all)

       - name: Upload boot.img
         uses: actions/upload-artifact@v4
         with:
           name: TWRP-berlna-boot
           path: ~/twrp/out/target/product/berlna/boot.img

       - name: Upload dtb and dtbo
         uses: actions/upload-artifact@v4
         with:
           name: TWRP-berlna-dtb
           path: |
             ~/twrp/device/motorola/berlna/prebuilt/dtb.img
             ~/twrp/device/motorola/berlna/prebuilt/dtbo.img
